input_a = float(input("first number>"))
input_b = float(input("second number>"))
print("덧셈 결과:",input_a + input_b)
print("뺄셈 결과:",input_a - input_b)
print("곱셈 결과:",input_a * input_b)
print("나눗셈 결과:",input_a / input_b)
